name: C/C++ CI

on:
  push:
    branches: chrysalis

jobs:
  cmake_build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
        
    - name: Check CMake Version
      run: cmake -version
    - name: CMake Build
      run: |
        mkdir build && cd build
        cmake -DCMAKE_INSTALL_PREFIX=$PWD ..
        make -j8
        make test

  ref_crypto_build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
        
    - name: Check CMake Version
      run: cmake -version
    - name: CMake Build
      run: |
        mkdir build && cd build
        cmake -DCMAKE_INSTALL_PREFIX=$PWD -DUSE_REF_CRYPTO=ON ..
        make -j8
        make test