name: build/test

on:
  push:
    branches: chrysalis

jobs:
  cmake_build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: install requirements
      run: |
        sudo apt update
        sudo apt install -y cppcheck ninja-build libcurl4-openssl-dev clang-format build-essential

    - name: Check CMake Version
      run: cmake -version

    - name: CMake Build
      run: |
        mkdir build && cd build
        cmake -DCMAKE_INSTALL_PREFIX=$PWD -DIOTA_TESTS=ON ..
        make -j8
        make test

  ref_crypto_build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: install requirements
      run: |
        sudo apt update
        sudo apt install -y cppcheck ninja-build libcurl4-openssl-dev clang-format build-essential

    - name: Check CMake Version
      run: cmake -version

    - name: CMake Build
      run: |
        mkdir build && cd build
        cmake -DCMAKE_INSTALL_PREFIX=$PWD -DIOTA_TESTS=ON -DIOTA_WALLET_ENABLE=ON ..
        make -j8
        make test